### ISSUE TITLE
Interview crashes when there is no one on other side of the case

### ISSUE THREAD

**Issue by ianeis** [SuffolkLITLab/docassemble-MtntoImpound#8]

**Comment by ianeis** [comment]
![Teams_ccLeQvIDox](https://user-images.githubusercontent.com/6284233/193895548-0c513955-3159-4451-9eee-d5fa402ff21a.png)

**Comment by ianeis** [comment]
```
Error
[Retry](https://apps-dev.suffolklitlab.org/interview?i=docassemble.playground234MtntoImpound%3AMtn_to_Impound_final.yml#)

IndexError: list index out of range
History
Ran initial code at 0.00000s
(from al_saved_sessions.yml)

initial: True
code: |
  ########### Save title and progress to session list ##################
  if get_config("assembly line",{}).get("update session metadata"):
    # To limit impact on DB, save progress every 3 steps or when progress is 100 +- 1
    if get_progress() > 99 or int(_internal.get('steps',1)) % 3 == 1:
      al_temp_metadata = get_interview_metadata(
        user_info().filename, user_info().session
      )
      al_temp_metadata["auto_title"] = str(al_sessions_interview_title)
      al_temp_metadata["progress"] = get_progress()
      set_current_session_metadata(al_temp_metadata)
      del(al_temp_metadata)
Ran initial code at 0.00003s
(from al_visual.yml)

initial: True
code: |
  # Set the dropdown/hamburger menu items
  # by default we just add a "Start over" link
  if _internal.get('steps') > 1:
    menu_items = al_menu_items
  else:
    menu_items = al_menu_items[1:] # Skip the "start over" menu item
Needed definition of al_menu_items at 0.00007s
Tried to run block at 0.00013s
(from al_visual.yml)

reconsider: True
code: |
  al_menu_items_tmp = [
    {"url": url_ask(['al_start_over_confirmation','al_start_over']),
    "label": "Start over"
    },
  ]
  
  # Answer set feature is behind a server-wide configuration option
  if get_config('assembly line',{}).get('enable answer sets'):
    al_menu_items_tmp.extend([
    {"url": url_ask(["al_sessions_snapshot_label", {"recompute": ["al_sessions_save_session_snapshot"]}, "al_sessions_save_status"]),
    "label": "Save answer set"
    },
    action_menu_item("Load answer set", "al_load_saved_session"),
  ]
  )
  
  if get_config('assembly line',{}).get('enable answer set imports'):
    al_menu_items_tmp.append(
      {"url": url_ask(["al_sessions_json_file", {"recompute": ["al_sessions_import_json"]}, "al_sessions_load_status"]),
      "label": "Import answer set"
      }
    )
    
  al_menu_items = al_menu_items_tmp
  del al_menu_items_tmp
Ran initial code at 0.00097s
(from al_saved_sessions.yml)

initial: True
code: |
  ########### Save title and progress to session list ##################
  if get_config("assembly line",{}).get("update session metadata"):
    # To limit impact on DB, save progress every 3 steps or when progress is 100 +- 1
    if get_progress() > 99 or int(_internal.get('steps',1)) % 3 == 1:
      al_temp_metadata = get_interview_metadata(
        user_info().filename, user_info().session
      )
      al_temp_metadata["auto_title"] = str(al_sessions_interview_title)
      al_temp_metadata["progress"] = get_progress()
      set_current_session_metadata(al_temp_metadata)
      del(al_temp_metadata)
Ran initial code at 0.00099s
(from al_visual.yml)

initial: True
code: |
  # Set the dropdown/hamburger menu items
  # by default we just add a "Start over" link
  if _internal.get('steps') > 1:
    menu_items = al_menu_items
  else:
    menu_items = al_menu_items[1:] # Skip the "start over" menu item
Tried to load objects from file at 0.00118s
(from docassemble.ALMassachusetts:al_massachusetts.yml)

objects from file:
  - court_emails : court_emails.yml
Tried to ask mandatory question at 0.02450s
progress: 100
mandatory: True
id: Your form is ready to download and file
question: |
  Your form is ready to download and file
subquestion: |
  Thank you ${users}. Your form is ready to download and deliver.
  
  Below is a preview of your form.
  
  ${pdf_concatenate(Mtn_to_Impound_final_attachment['final'], filename='Mtn_to_Impound_final.pdf') }
need: Mtn_to_Impound_final
attachment code: Mtn_to_Impound_final_attachment['final']
Needed definition of Mtn_to_Impound_final at 0.02455s
Tried to run block at 0.02460s
id: interview_order_Mtn_to_Impound_final
code: |
  # This is a placeholder to control logic flow in this interview

  basic_questions_intro_screen 
  Mtn_to_Impound_final_intro
  # Set the allowed courts for this interview
  allowed_courts = interview_metadata["Mtn_to_Impound_final"]["allowed courts"]
  nav.set_section('review_Mtn_to_Impound_final')
  # Below sets the user_role by asking a question.
  # You can set user_role directly instead to either 'plaintiff' or 'defendant'
  user_ask_role
  if len(users) > 1:
    multiple_users # event name
  trial_court.address.county
  str(docket_numbers)
  str(other_parties)
  other_parties[0].address
  affidavit_narrative
  delivery_mode
  str(users)
  signature_date
  # Set the answer file name.
  set_parts(subtitle=str(users))
  set_progress(14.29)
  set_progress(28.57)
  # Save (anonymized) interview statistics.
  store_variables_snapshot(
    persistent=True,
    data={'zip': showifdef("users[0].address.zip"), "reached_interview_end": True})
  Mtn_to_Impound_final_preview_question # Pre-canned preview screen
  basic_questions_signature_flow
  Mtn_to_Impound_final = True
[Show variables and values](https://apps-dev.suffolklitlab.org/vars?i=docassemble.playground234MtntoImpound%3AMtn_to_Impound_final.yml)

Log
Traceback (most recent call last):
  File "/usr/share/docassemble/local3.10/lib/python3.10/site-packages/docassemble/base/parse.py", line 8038, in assemble
    interview_status.populate(question.ask(user_dict, old_user_dict, 'None', [], None, None))
  File "/usr/share/docassemble/local3.10/lib/python3.10/site-packages/docassemble/base/parse.py", line 5094, in ask
    eval(need_code, user_dict)
  File "<need expression>", line 1, in <module>
NameError: name 'Mtn_to_Impound_final' is not defined

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/share/docassemble/local3.10/lib/python3.10/site-packages/docassemble/base/util.py", line 2281, in __getitem__
    return self.elements[index]
IndexError: list index out of range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/share/docassemble/local3.10/lib/python3.10/site-packages/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/share/docassemble/local3.10/lib/python3.10/site-packages/flask/app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/usr/share/docassemble/local3.10/lib/python3.10/site-packages/docassemble/webapp/server.py", line 8077, in index
    interview.assemble(user_dict, interview_status, old_user_dict, force_question=special_question)
  File "/usr/share/docassemble/local3.10/lib/python3.10/site-packages/docassemble/base/parse.py", line 8296, in assemble
    raise the_error
  File "/usr/share/docassemble/local3.10/lib/python3.10/site-packages/docassemble/base/parse.py", line 8083, in assemble
    question_result = self.askfor(missingVariable, user_dict, old_user_dict, interview_status, seeking=interview_status.seeking, follow_mc=follow_mc, seeking_question=seeking_question)
  File "/usr/share/docassemble/local3.10/lib/python3.10/site-packages/docassemble/base/parse.py", line 8746, in askfor
    exec_with_trap(question, user_dict)
  File "/usr/share/docassemble/local3.10/lib/python3.10/site-packages/docassemble/base/parse.py", line 9366, in exec_with_trap
    exec(the_question.compute, the_dict)
  File "<code block>", line 16, in <module>
  File "/usr/share/docassemble/local3.10/lib/python3.10/site-packages/docassemble/base/util.py", line 2288, in __getitem__
    raise IndexError("list index out of range")
IndexError: list index out of range
```
